# .github/workflows/generate-image.yml
name: Generate Daily Share Image

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Puppeteer dependencies
        run: sudo apt-get update && sudo apt-get install -yq libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf-2.0-0 libgtk-3-0 libgbm1 libnss3 libxss1 libasound2t64

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run script to generate image
        run: node generate-image.js

      # === NOV KORAK: Cache Busting ===
      # Ta korak posodobi verzijo slike v HTML datoteki.
      - name: Update image version in HTML
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s|share-image.png?v=[0-9]*|share-image.png?v=${TIMESTAMP}|g" index.html
          echo "HTML meta tags updated with version ${TIMESTAMP}"

      # Ta korak zdaj shrani spremembe v obeh datotekah
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Avtomatsko posodobljena slika in HTML za deljenje'
          file_pattern: 'share-image.png index.html'